from typing import TypedDict, List, Annotated
import operator

class AgentState(TypedDict):
    # Using Annotated with operator.add ensures that messages 
    # are appended to the history rather than replaced.
    messages: Annotated[List[dict], operator.add] #TO maintain a history of messages exchanged with the agent (4 message , AI, user, sytem, context/vectorDB)
    current_query: str                            #The query currently being processed by the agent
    documents: List[str]                          #List of relevant documents retrieved for the current query
    plan: List[str]                               #The step-by-step plan of actions to be taken by the agent (Where to go next)
    status: str                                   #The current status of the agent (e.g., "conversational", "technical", "research", etc.)  
    final_answer: str                             #Final message or response generated by the agent after processing the query and documents